blank_issues_enabled: false
contact_links:
  - name: Existing Issues
    url: https://github.com/tsuyoshi-otake/otak-proxy/issues?q=is%3Aissue
    about: Please check if a similar issue already exists